-- 1. What is the total revenue generated by male vs female customers?
select 	gender,
		SUM(purchase_amount)
from customer
group by gender


-- 2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where 	discount_applied = 'Yes' 
		and purchase_amount >= (select AVG(purchase_amount) from customer)
order by purchase_amount desc


-- 3. Which are the top 5 products with the highest average review rating?
select item_purchased,
	round(avg(review_rating::numeric),2) as "Average review rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


-- 4. Compare the average purchase amounts between Standard and Express Shipping
select shipping_type,
	round(avg(purchase_amount),2) as "Average purchase amount"
from customer
where shipping_type in ('Express','Standard')
group by shipping_type


-- 5. Do subscribed customers spend more? Compare average spend and 
-- total revenue between subscribers and non- subscribers
select subscription_status,
	count(customer_id) as "Total customers",
	sum(purchase_amount) as "Total revenue",
	round(avg(purchase_amount),2) as "Average purchase amount" 
from customer
group by subscription_status
order by "Total revenue" desc


-- 6. Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
	round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

-- 7. Segment customers into New, Returning, and Loyal based on their total number
-- of previous purchases, and show the count of each segment.
with customer_type as(
	select 	customer_id, 
			previous_purchases,
			case 
				when previous_purchases = 1 then 'New'
				when previous_purchases between 2 and 10 then 'Returning'
				else 'Loyal'
				end as customer_segment
	from customer
)

select customer_segment, count(*) as total_customer
from customer_type
group by customer_segment
order by total_customer desc


-- 8. What are the top 3 most purchased products within each category?
with item_counts as(
	select 	category, item_purchased,
			count(customer_id) as total_orders,
			row_number() over (partition by category order by count(customer_id) desc) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3


-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


-- 10. What is the revenue contribution of each age group?
select age_group,
	sum(purchase_amount) as "revenue contribution"
from customer
group by age_group
order by "revenue contribution" desc